dir: ".tmux"
links:
  - "tmux.conf:.tmux"
  - "tmux-*.conf:.tmux"
  - "tmux.$OS.conf:.tmux"
  - path: "*:.tmux"
    type: directory
lines:
  - path: ".tmux.conf"
    line: "source-file ~/.tmux/tmux.conf"
