dir: ".tmux"
links:
  - ".tmux/tmux.conf"
  - ".tmux/tmux-*.conf"
  - ".tmux/tmux.$OS.conf"
  - path: ".tmux/*"
    type: directory
lines:
  - file: ".tmux.conf"
    line: "source-file ~/.tmux/tmux.conf"
