---
role:
  pkg:
    - tmux
    - name: reattach-to-user-namespace
      os: ["darwin"]
  dir: .tmux
  link:
    - "tmux.conf:.tmux"
    - "tmux-*.conf:.tmux"
    - "tmux.$OS.conf:.tmux"
    - "colors:.tmux"
  line:
    ".tmux.conf": "source-file $HOME/.tmux/tmux.conf"
