link:
  - "tmux.conf:.tmux"
  - "tmux-*.conf:.tmux"
  - "tmux.$OS.conf:.tmux"
  - "colors:.tmux"
exec:
  - |
    if ! test -f "$HOME/.tmux.conf" || ! grep -Fxq 'source-file $HOME/.tmux/tmux.conf' "$HOME/.tmux.conf"; then
      echo 'source-file $HOME/.tmux/tmux.conf' >> "$HOME/.tmux.conf";
    fi;
